### ISSUE TITLE
Envrionments plugin: provide instance methods too?

### ISSUE THREAD

**Issue by singpolyma** [jeremyevans/roda#213] opened 2021-09-02 02:06 UTC
Especially useful with, say, assets plugin for:

```
route do |r|
    r.assets if production?
end
```

**Comment by jeremyevans** [comment] 2021-09-02 02:55
I'm on the fence about this.  If you would like it added, please open a thread on the Google Group and see what the community thinks about the idea.  Such methods are easy to define yourself, or you can just use `self.class.production?`.

I'm going to close this now as it is not a bug in Roda.  As the contribution guidelines state, GitHub Issues is only supposed to be used for bug reports.  Questions about Roda and feature requests should be posted on the Google Group.

**Closed by jeremyevans** 2021-09-02 02:55 UTC
